const __root = @This();
pub const __builtin = @import("std").zig.c_translation.builtins;
pub const __helpers = @import("std").zig.c_translation.helpers;

pub const off_t = c_long;
pub const pid_t = c_int;
pub const uid_t = c_uint;
pub const gid_t = c_uint;
pub const useconds_t = c_uint;
pub extern fn pipe([*c]c_int) c_int;
pub extern fn pipe2([*c]c_int, c_int) c_int;
pub extern fn close(c_int) c_int;
pub extern fn posix_close(c_int, c_int) c_int;
pub extern fn dup(c_int) c_int;
pub extern fn dup2(c_int, c_int) c_int;
pub extern fn dup3(c_int, c_int, c_int) c_int;
pub extern fn lseek(c_int, off_t, c_int) off_t;
pub extern fn fsync(c_int) c_int;
pub extern fn fdatasync(c_int) c_int;
pub extern fn read(c_int, ?*anyopaque, usize) isize;
pub extern fn write(c_int, ?*const anyopaque, usize) isize;
pub extern fn pread(c_int, ?*anyopaque, usize, off_t) isize;
pub extern fn pwrite(c_int, ?*const anyopaque, usize, off_t) isize;
pub extern fn chown([*c]const u8, uid_t, gid_t) c_int;
pub extern fn fchown(c_int, uid_t, gid_t) c_int;
pub extern fn lchown([*c]const u8, uid_t, gid_t) c_int;
pub extern fn fchownat(c_int, [*c]const u8, uid_t, gid_t, c_int) c_int;
pub extern fn link([*c]const u8, [*c]const u8) c_int;
pub extern fn linkat(c_int, [*c]const u8, c_int, [*c]const u8, c_int) c_int;
pub extern fn symlink([*c]const u8, [*c]const u8) c_int;
pub extern fn symlinkat([*c]const u8, c_int, [*c]const u8) c_int;
pub extern fn readlink(noalias [*c]const u8, noalias [*c]u8, usize) isize;
pub extern fn readlinkat(c_int, noalias [*c]const u8, noalias [*c]u8, usize) isize;
pub extern fn unlink([*c]const u8) c_int;
pub extern fn unlinkat(c_int, [*c]const u8, c_int) c_int;
pub extern fn rmdir([*c]const u8) c_int;
pub extern fn truncate([*c]const u8, off_t) c_int;
pub extern fn ftruncate(c_int, off_t) c_int;
pub extern fn access([*c]const u8, c_int) c_int;
pub extern fn faccessat(c_int, [*c]const u8, c_int, c_int) c_int;
pub extern fn chdir([*c]const u8) c_int;
pub extern fn fchdir(c_int) c_int;
pub extern fn getcwd([*c]u8, usize) [*c]u8;
pub extern fn alarm(c_uint) c_uint;
pub extern fn sleep(c_uint) c_uint;
pub extern fn pause() c_int;
pub extern fn fork() pid_t;
pub extern fn _Fork() pid_t;
pub extern fn execve([*c]const u8, [*c]const [*c]u8, [*c]const [*c]u8) c_int;
pub extern fn execv([*c]const u8, [*c]const [*c]u8) c_int;
pub extern fn execle([*c]const u8, [*c]const u8, ...) c_int;
pub extern fn execl([*c]const u8, [*c]const u8, ...) c_int;
pub extern fn execvp([*c]const u8, [*c]const [*c]u8) c_int;
pub extern fn execlp([*c]const u8, [*c]const u8, ...) c_int;
pub extern fn fexecve(c_int, [*c]const [*c]u8, [*c]const [*c]u8) c_int;
pub extern fn _exit(c_int) noreturn;
pub extern fn getpid() pid_t;
pub extern fn getppid() pid_t;
pub extern fn getpgrp() pid_t;
pub extern fn getpgid(pid_t) pid_t;
pub extern fn setpgid(pid_t, pid_t) c_int;
pub extern fn setsid() pid_t;
pub extern fn getsid(pid_t) pid_t;
pub extern fn ttyname(c_int) [*c]u8;
pub extern fn ttyname_r(c_int, [*c]u8, usize) c_int;
pub extern fn isatty(c_int) c_int;
pub extern fn tcgetpgrp(c_int) pid_t;
pub extern fn tcsetpgrp(c_int, pid_t) c_int;
pub extern fn getuid() uid_t;
pub extern fn geteuid() uid_t;
pub extern fn getgid() gid_t;
pub extern fn getegid() gid_t;
pub extern fn getgroups(c_int, [*c]gid_t) c_int;
pub extern fn setuid(uid_t) c_int;
pub extern fn seteuid(uid_t) c_int;
pub extern fn setgid(gid_t) c_int;
pub extern fn setegid(gid_t) c_int;
pub extern fn getlogin() [*c]u8;
pub extern fn getlogin_r([*c]u8, usize) c_int;
pub extern fn gethostname([*c]u8, usize) c_int;
pub extern fn ctermid([*c]u8) [*c]u8;
pub extern fn getopt(c_int, [*c]const [*c]u8, [*c]const u8) c_int;
pub extern var optarg: [*c]u8;
pub extern var optind: c_int;
pub extern var opterr: c_int;
pub extern var optopt: c_int;
pub extern fn pathconf([*c]const u8, c_int) c_long;
pub extern fn fpathconf(c_int, c_int) c_long;
pub extern fn sysconf(c_int) c_long;
pub extern fn confstr(c_int, [*c]u8, usize) usize;
pub extern fn setreuid(uid_t, uid_t) c_int;
pub extern fn setregid(gid_t, gid_t) c_int;
pub extern fn lockf(c_int, c_int, off_t) c_int;
pub extern fn gethostid() c_long;
pub extern fn nice(c_int) c_int;
pub extern fn sync() void;
pub extern fn setpgrp() pid_t;
pub extern fn crypt([*c]const u8, [*c]const u8) [*c]u8;
pub extern fn encrypt([*c]u8, c_int) void;
pub extern fn swab(noalias ?*const anyopaque, noalias ?*anyopaque, isize) void;
pub extern fn usleep(c_uint) c_int;
pub extern fn ualarm(c_uint, c_uint) c_uint;
pub extern fn brk(?*anyopaque) c_int;
pub extern fn sbrk(isize) ?*anyopaque;
pub extern fn vfork() pid_t;
pub extern fn vhangup() c_int;
pub extern fn chroot([*c]const u8) c_int;
pub extern fn getpagesize() c_int;
pub extern fn getdtablesize() c_int;
pub extern fn sethostname([*c]const u8, usize) c_int;
pub extern fn getdomainname([*c]u8, usize) c_int;
pub extern fn setdomainname([*c]const u8, usize) c_int;
pub extern fn setgroups(usize, [*c]const gid_t) c_int;
pub extern fn getpass([*c]const u8) [*c]u8;
pub extern fn daemon(c_int, c_int) c_int;
pub extern fn setusershell() void;
pub extern fn endusershell() void;
pub extern fn getusershell() [*c]u8;
pub extern fn acct([*c]const u8) c_int;
pub extern fn syscall(c_long, ...) c_long;
pub extern fn execvpe([*c]const u8, [*c]const [*c]u8, [*c]const [*c]u8) c_int;
pub extern fn issetugid() c_int;
pub extern fn getentropy(?*anyopaque, usize) c_int;
pub extern var optreset: c_int;
pub const wchar_t = c_int;
pub extern fn atoi([*c]const u8) c_int;
pub extern fn atol([*c]const u8) c_long;
pub extern fn atoll([*c]const u8) c_longlong;
pub extern fn atof([*c]const u8) f64;
pub extern fn strtof(noalias [*c]const u8, noalias [*c][*c]u8) f32;
pub extern fn strtod(noalias [*c]const u8, noalias [*c][*c]u8) f64;
pub extern fn strtold(noalias [*c]const u8, noalias [*c][*c]u8) c_longdouble;
pub extern fn strtol(noalias [*c]const u8, noalias [*c][*c]u8, c_int) c_long;
pub extern fn strtoul(noalias [*c]const u8, noalias [*c][*c]u8, c_int) c_ulong;
pub extern fn strtoll(noalias [*c]const u8, noalias [*c][*c]u8, c_int) c_longlong;
pub extern fn strtoull(noalias [*c]const u8, noalias [*c][*c]u8, c_int) c_ulonglong;
pub extern fn rand() c_int;
pub extern fn srand(c_uint) void;
pub extern fn malloc(usize) ?*anyopaque;
pub extern fn calloc(usize, usize) ?*anyopaque;
pub extern fn realloc(?*anyopaque, usize) ?*anyopaque;
pub extern fn free(?*anyopaque) void;
pub extern fn aligned_alloc(usize, usize) ?*anyopaque;
pub extern fn abort() noreturn;
pub extern fn atexit(?*const fn () callconv(.c) void) c_int;
pub extern fn exit(c_int) noreturn;
pub extern fn _Exit(c_int) noreturn;
pub extern fn at_quick_exit(?*const fn () callconv(.c) void) c_int;
pub extern fn quick_exit(c_int) noreturn;
pub extern fn getenv([*c]const u8) [*c]u8;
pub extern fn system([*c]const u8) c_int;
pub extern fn bsearch(?*const anyopaque, ?*const anyopaque, usize, usize, ?*const fn (?*const anyopaque, ?*const anyopaque) callconv(.c) c_int) ?*anyopaque;
pub extern fn qsort(?*anyopaque, usize, usize, ?*const fn (?*const anyopaque, ?*const anyopaque) callconv(.c) c_int) void;
pub extern fn abs(c_int) c_int;
pub extern fn labs(c_long) c_long;
pub extern fn llabs(c_longlong) c_longlong;
pub const div_t = extern struct {
    quot: c_int = 0,
    rem: c_int = 0,
};
pub const ldiv_t = extern struct {
    quot: c_long = 0,
    rem: c_long = 0,
};
pub const lldiv_t = extern struct {
    quot: c_longlong = 0,
    rem: c_longlong = 0,
};
pub extern fn div(c_int, c_int) div_t;
pub extern fn ldiv(c_long, c_long) ldiv_t;
pub extern fn lldiv(c_longlong, c_longlong) lldiv_t;
pub extern fn mblen([*c]const u8, usize) c_int;
pub extern fn mbtowc(noalias [*c]wchar_t, noalias [*c]const u8, usize) c_int;
pub extern fn wctomb([*c]u8, wchar_t) c_int;
pub extern fn mbstowcs(noalias [*c]wchar_t, noalias [*c]const u8, usize) usize;
pub extern fn wcstombs(noalias [*c]u8, noalias [*c]const wchar_t, usize) usize;
pub extern fn __ctype_get_mb_cur_max() usize;
pub extern fn posix_memalign([*c]?*anyopaque, usize, usize) c_int;
pub extern fn setenv([*c]const u8, [*c]const u8, c_int) c_int;
pub extern fn unsetenv([*c]const u8) c_int;
pub extern fn mkstemp([*c]u8) c_int;
pub extern fn mkostemp([*c]u8, c_int) c_int;
pub extern fn mkdtemp([*c]u8) [*c]u8;
pub extern fn getsubopt([*c][*c]u8, [*c]const [*c]u8, [*c][*c]u8) c_int;
pub extern fn rand_r([*c]c_uint) c_int;
pub extern fn realpath(noalias [*c]const u8, noalias [*c]u8) [*c]u8;
pub extern fn random() c_long;
pub extern fn srandom(c_uint) void;
pub extern fn initstate(c_uint, [*c]u8, usize) [*c]u8;
pub extern fn setstate([*c]u8) [*c]u8;
pub extern fn putenv([*c]u8) c_int;
pub extern fn posix_openpt(c_int) c_int;
pub extern fn grantpt(c_int) c_int;
pub extern fn unlockpt(c_int) c_int;
pub extern fn ptsname(c_int) [*c]u8;
pub extern fn l64a(c_long) [*c]u8;
pub extern fn a64l([*c]const u8) c_long;
pub extern fn setkey([*c]const u8) void;
pub extern fn drand48() f64;
pub extern fn erand48([*c]c_ushort) f64;
pub extern fn lrand48() c_long;
pub extern fn nrand48([*c]c_ushort) c_long;
pub extern fn mrand48() c_long;
pub extern fn jrand48([*c]c_ushort) c_long;
pub extern fn srand48(c_long) void;
pub extern fn seed48([*c]c_ushort) [*c]c_ushort;
pub extern fn lcong48([*c]c_ushort) void;
pub extern fn alloca(usize) ?*anyopaque;
pub extern fn mktemp([*c]u8) [*c]u8;
pub extern fn mkstemps([*c]u8, c_int) c_int;
pub extern fn mkostemps([*c]u8, c_int, c_int) c_int;
pub extern fn valloc(usize) ?*anyopaque;
pub extern fn memalign(usize, usize) ?*anyopaque;
pub extern fn getloadavg([*c]f64, c_int) c_int;
pub extern fn clearenv() c_int;
pub extern fn reallocarray(?*anyopaque, usize, usize) ?*anyopaque;
pub extern fn qsort_r(?*anyopaque, usize, usize, ?*const fn (?*const anyopaque, ?*const anyopaque, ?*anyopaque) callconv(.c) c_int, ?*anyopaque) void;

pub const __VERSION__ = "Aro aro-zig";
pub const __Aro__ = "";
pub const __STDC__ = @as(c_int, 1);
pub const __STDC_HOSTED__ = @as(c_int, 1);
pub const __STDC_UTF_16__ = @as(c_int, 1);
pub const __STDC_UTF_32__ = @as(c_int, 1);
pub const __STDC_EMBED_NOT_FOUND__ = @as(c_int, 0);
pub const __STDC_EMBED_FOUND__ = @as(c_int, 1);
pub const __STDC_EMBED_EMPTY__ = @as(c_int, 2);
pub const __STDC_VERSION__ = @as(c_long, 201710);
pub const __GNUC__ = @as(c_int, 7);
pub const __GNUC_MINOR__ = @as(c_int, 1);
pub const __GNUC_PATCHLEVEL__ = @as(c_int, 0);
pub const __ARO_EMULATE_CLANG__ = @as(c_int, 1);
pub const __ARO_EMULATE_GCC__ = @as(c_int, 2);
pub const __ARO_EMULATE_MSVC__ = @as(c_int, 3);
pub const __ARO_EMULATE__ = __ARO_EMULATE_GCC__;
pub inline fn __building_module(x: anytype) @TypeOf(@as(c_int, 0)) {
    _ = &x;
    return @as(c_int, 0);
}
pub const __OPTIMIZE__ = @as(c_int, 1);
pub const linux = @as(c_int, 1);
pub const __linux = @as(c_int, 1);
pub const __linux__ = @as(c_int, 1);
pub const unix = @as(c_int, 1);
pub const __unix = @as(c_int, 1);
pub const __unix__ = @as(c_int, 1);
pub const __code_model_small__ = @as(c_int, 1);
pub const __amd64__ = @as(c_int, 1);
pub const __amd64 = @as(c_int, 1);
pub const __x86_64__ = @as(c_int, 1);
pub const __x86_64 = @as(c_int, 1);
pub const __SEG_GS = @as(c_int, 1);
pub const __SEG_FS = @as(c_int, 1);
pub const __seg_gs = @compileError("unable to translate macro: undefined identifier `address_space`"); // <builtin>:33:9
pub const __seg_fs = @compileError("unable to translate macro: undefined identifier `address_space`"); // <builtin>:34:9
pub const __LAHF_SAHF__ = @as(c_int, 1);
pub const __AES__ = @as(c_int, 1);
pub const __VAES__ = @as(c_int, 1);
pub const __PCLMUL__ = @as(c_int, 1);
pub const __VPCLMULQDQ__ = @as(c_int, 1);
pub const __LZCNT__ = @as(c_int, 1);
pub const __RDRND__ = @as(c_int, 1);
pub const __FSGSBASE__ = @as(c_int, 1);
pub const __BMI__ = @as(c_int, 1);
pub const __BMI2__ = @as(c_int, 1);
pub const __POPCNT__ = @as(c_int, 1);
pub const __PRFCHW__ = @as(c_int, 1);
pub const __RDSEED__ = @as(c_int, 1);
pub const __ADX__ = @as(c_int, 1);
pub const __MWAITX__ = @as(c_int, 1);
pub const __MOVBE__ = @as(c_int, 1);
pub const __SSE4A__ = @as(c_int, 1);
pub const __FMA__ = @as(c_int, 1);
pub const __F16C__ = @as(c_int, 1);
pub const __SHA__ = @as(c_int, 1);
pub const __FXSR__ = @as(c_int, 1);
pub const __XSAVE__ = @as(c_int, 1);
pub const __XSAVEOPT__ = @as(c_int, 1);
pub const __XSAVEC__ = @as(c_int, 1);
pub const __XSAVES__ = @as(c_int, 1);
pub const __PKU__ = @as(c_int, 1);
pub const __CLFLUSHOPT__ = @as(c_int, 1);
pub const __CLWB__ = @as(c_int, 1);
pub const __WBNOINVD__ = @as(c_int, 1);
pub const __SHSTK__ = @as(c_int, 1);
pub const __CLZERO__ = @as(c_int, 1);
pub const __RDPID__ = @as(c_int, 1);
pub const __RDPRU__ = @as(c_int, 1);
pub const __INVPCID__ = @as(c_int, 1);
pub const __CRC32__ = @as(c_int, 1);
pub const __AVX2__ = @as(c_int, 1);
pub const __AVX__ = @as(c_int, 1);
pub const __SSE4_2__ = @as(c_int, 1);
pub const __SSE4_1__ = @as(c_int, 1);
pub const __SSSE3__ = @as(c_int, 1);
pub const __SSE3__ = @as(c_int, 1);
pub const __SSE2__ = @as(c_int, 1);
pub const __SSE__ = @as(c_int, 1);
pub const __SSE_MATH__ = @as(c_int, 1);
pub const __MMX__ = @as(c_int, 1);
pub const __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 = @as(c_int, 1);
pub const __SIZEOF_FLOAT128__ = @as(c_int, 16);
pub const _LP64 = @as(c_int, 1);
pub const __LP64__ = @as(c_int, 1);
pub const __FLOAT128__ = @as(c_int, 1);
pub const __ORDER_LITTLE_ENDIAN__ = @as(c_int, 1234);
pub const __ORDER_BIG_ENDIAN__ = @as(c_int, 4321);
pub const __ORDER_PDP_ENDIAN__ = @as(c_int, 3412);
pub const __BYTE_ORDER__ = __ORDER_LITTLE_ENDIAN__;
pub const __LITTLE_ENDIAN__ = @as(c_int, 1);
pub const __ELF__ = @as(c_int, 1);
pub const __ATOMIC_RELAXED = @as(c_int, 0);
pub const __ATOMIC_CONSUME = @as(c_int, 1);
pub const __ATOMIC_ACQUIRE = @as(c_int, 2);
pub const __ATOMIC_RELEASE = @as(c_int, 3);
pub const __ATOMIC_ACQ_REL = @as(c_int, 4);
pub const __ATOMIC_SEQ_CST = @as(c_int, 5);
pub const __ATOMIC_BOOL_LOCK_FREE = @as(c_int, 1);
pub const __ATOMIC_CHAR_LOCK_FREE = @as(c_int, 1);
pub const __ATOMIC_CHAR16_T_LOCK_FREE = @as(c_int, 1);
pub const __ATOMIC_CHAR32_T_LOCK_FREE = @as(c_int, 1);
pub const __ATOMIC_WCHAR_T_LOCK_FREE = @as(c_int, 1);
pub const __ATOMIC_SHORT_LOCK_FREE = @as(c_int, 1);
pub const __ATOMIC_INT_LOCK_FREE = @as(c_int, 1);
pub const __ATOMIC_LONG_LOCK_FREE = @as(c_int, 1);
pub const __ATOMIC_LLONG_LOCK_FREE = @as(c_int, 1);
pub const __ATOMIC_POINTER_LOCK_FREE = @as(c_int, 1);
pub const __CHAR_BIT__ = @as(c_int, 8);
pub const __BOOL_WIDTH__ = @as(c_int, 8);
pub const __SCHAR_MAX__ = @as(c_int, 127);
pub const __SCHAR_WIDTH__ = @as(c_int, 8);
pub const __SHRT_MAX__ = @as(c_int, 32767);
pub const __SHRT_WIDTH__ = @as(c_int, 16);
pub const __INT_MAX__ = __helpers.promoteIntLiteral(c_int, 2147483647, .decimal);
pub const __INT_WIDTH__ = @as(c_int, 32);
pub const __LONG_MAX__ = __helpers.promoteIntLiteral(c_long, 9223372036854775807, .decimal);
pub const __LONG_WIDTH__ = @as(c_int, 64);
pub const __LONG_LONG_MAX__ = @as(c_longlong, 9223372036854775807);
pub const __LONG_LONG_WIDTH__ = @as(c_int, 64);
pub const __WCHAR_MAX__ = __helpers.promoteIntLiteral(c_int, 2147483647, .decimal);
pub const __WCHAR_WIDTH__ = @as(c_int, 32);
pub const __INTMAX_MAX__ = __helpers.promoteIntLiteral(c_long, 9223372036854775807, .decimal);
pub const __INTMAX_WIDTH__ = @as(c_int, 64);
pub const __SIZE_MAX__ = __helpers.promoteIntLiteral(c_ulong, 18446744073709551615, .decimal);
pub const __SIZE_WIDTH__ = @as(c_int, 64);
pub const __UINTMAX_MAX__ = __helpers.promoteIntLiteral(c_ulong, 18446744073709551615, .decimal);
pub const __UINTMAX_WIDTH__ = @as(c_int, 64);
pub const __PTRDIFF_MAX__ = __helpers.promoteIntLiteral(c_long, 9223372036854775807, .decimal);
pub const __PTRDIFF_WIDTH__ = @as(c_int, 64);
pub const __INTPTR_MAX__ = __helpers.promoteIntLiteral(c_long, 9223372036854775807, .decimal);
pub const __INTPTR_WIDTH__ = @as(c_int, 64);
pub const __UINTPTR_MAX__ = __helpers.promoteIntLiteral(c_ulong, 18446744073709551615, .decimal);
pub const __UINTPTR_WIDTH__ = @as(c_int, 64);
pub const __SIG_ATOMIC_MAX__ = __helpers.promoteIntLiteral(c_int, 2147483647, .decimal);
pub const __SIG_ATOMIC_WIDTH__ = @as(c_int, 32);
pub const __BITINT_MAXWIDTH__ = __helpers.promoteIntLiteral(c_int, 65535, .decimal);
pub const __SIZEOF_FLOAT__ = @as(c_int, 4);
pub const __SIZEOF_DOUBLE__ = @as(c_int, 8);
pub const __SIZEOF_LONG_DOUBLE__ = @as(c_int, 10);
pub const __SIZEOF_SHORT__ = @as(c_int, 2);
pub const __SIZEOF_INT__ = @as(c_int, 4);
pub const __SIZEOF_LONG__ = @as(c_int, 8);
pub const __SIZEOF_LONG_LONG__ = @as(c_int, 8);
pub const __SIZEOF_POINTER__ = @as(c_int, 8);
pub const __SIZEOF_PTRDIFF_T__ = @as(c_int, 8);
pub const __SIZEOF_SIZE_T__ = @as(c_int, 8);
pub const __SIZEOF_WCHAR_T__ = @as(c_int, 4);
pub const __SIZEOF_INT128__ = @as(c_int, 16);
pub const __INTPTR_TYPE__ = c_long;
pub const __UINTPTR_TYPE__ = c_ulong;
pub const __INTMAX_TYPE__ = c_long;
pub const __INTMAX_C_SUFFIX__ = @compileError("unable to translate macro: undefined identifier `L`"); // <builtin>:152:9
pub const __UINTMAX_TYPE__ = c_ulong;
pub const __UINTMAX_C_SUFFIX__ = @compileError("unable to translate macro: undefined identifier `UL`"); // <builtin>:154:9
pub const __PTRDIFF_TYPE__ = c_long;
pub const __SIZE_TYPE__ = c_ulong;
pub const __WCHAR_TYPE__ = c_int;
pub const __CHAR16_TYPE__ = c_ushort;
pub const __CHAR32_TYPE__ = c_uint;
pub const __INT8_TYPE__ = i8;
pub const __INT8_FMTd__ = "hhd";
pub const __INT8_FMTi__ = "hhi";
pub const __INT8_C_SUFFIX__ = "";
pub const __INT16_TYPE__ = c_short;
pub const __INT16_FMTd__ = "hd";
pub const __INT16_FMTi__ = "hi";
pub const __INT16_C_SUFFIX__ = "";
pub const __INT32_TYPE__ = c_int;
pub const __INT32_FMTd__ = "d";
pub const __INT32_FMTi__ = "i";
pub const __INT32_C_SUFFIX__ = "";
pub const __INT64_TYPE__ = c_long;
pub const __INT64_FMTd__ = "ld";
pub const __INT64_FMTi__ = "li";
pub const __INT64_C_SUFFIX__ = @compileError("unable to translate macro: undefined identifier `L`"); // <builtin>:175:9
pub const __UINT8_TYPE__ = u8;
pub const __UINT8_FMTo__ = "hho";
pub const __UINT8_FMTu__ = "hhu";
pub const __UINT8_FMTx__ = "hhx";
pub const __UINT8_FMTX__ = "hhX";
pub const __UINT8_C_SUFFIX__ = "";
pub const __UINT8_MAX__ = @as(c_int, 255);
pub const __INT8_MAX__ = @as(c_int, 127);
pub const __UINT16_TYPE__ = c_ushort;
pub const __UINT16_FMTo__ = "ho";
pub const __UINT16_FMTu__ = "hu";
pub const __UINT16_FMTx__ = "hx";
pub const __UINT16_FMTX__ = "hX";
pub const __UINT16_C_SUFFIX__ = "";
pub const __UINT16_MAX__ = __helpers.promoteIntLiteral(c_int, 65535, .decimal);
pub const __INT16_MAX__ = @as(c_int, 32767);
pub const __UINT32_TYPE__ = c_uint;
pub const __UINT32_FMTo__ = "o";
pub const __UINT32_FMTu__ = "u";
pub const __UINT32_FMTx__ = "x";
pub const __UINT32_FMTX__ = "X";
pub const __UINT32_C_SUFFIX__ = @compileError("unable to translate macro: undefined identifier `U`"); // <builtin>:197:9
pub const __UINT32_MAX__ = __helpers.promoteIntLiteral(c_uint, 4294967295, .decimal);
pub const __INT32_MAX__ = __helpers.promoteIntLiteral(c_int, 2147483647, .decimal);
pub const __UINT64_TYPE__ = c_ulong;
pub const __UINT64_FMTo__ = "lo";
pub const __UINT64_FMTu__ = "lu";
pub const __UINT64_FMTx__ = "lx";
pub const __UINT64_FMTX__ = "lX";
pub const __UINT64_C_SUFFIX__ = @compileError("unable to translate macro: undefined identifier `UL`"); // <builtin>:205:9
pub const __UINT64_MAX__ = __helpers.promoteIntLiteral(c_ulong, 18446744073709551615, .decimal);
pub const __INT64_MAX__ = __helpers.promoteIntLiteral(c_long, 9223372036854775807, .decimal);
pub const __INT_LEAST8_TYPE__ = i8;
pub const __INT_LEAST8_MAX__ = @as(c_int, 127);
pub const __INT_LEAST8_WIDTH__ = @as(c_int, 8);
pub const INT_LEAST8_FMTd__ = "hhd";
pub const INT_LEAST8_FMTi__ = "hhi";
pub const __UINT_LEAST8_TYPE__ = u8;
pub const __UINT_LEAST8_MAX__ = @as(c_int, 255);
pub const UINT_LEAST8_FMTo__ = "hho";
pub const UINT_LEAST8_FMTu__ = "hhu";
pub const UINT_LEAST8_FMTx__ = "hhx";
pub const UINT_LEAST8_FMTX__ = "hhX";
pub const __INT_FAST8_TYPE__ = i8;
pub const __INT_FAST8_MAX__ = @as(c_int, 127);
pub const __INT_FAST8_WIDTH__ = @as(c_int, 8);
pub const INT_FAST8_FMTd__ = "hhd";
pub const INT_FAST8_FMTi__ = "hhi";
pub const __UINT_FAST8_TYPE__ = u8;
pub const __UINT_FAST8_MAX__ = @as(c_int, 255);
pub const UINT_FAST8_FMTo__ = "hho";
pub const UINT_FAST8_FMTu__ = "hhu";
pub const UINT_FAST8_FMTx__ = "hhx";
pub const UINT_FAST8_FMTX__ = "hhX";
pub const __INT_LEAST16_TYPE__ = c_short;
pub const __INT_LEAST16_MAX__ = @as(c_int, 32767);
pub const __INT_LEAST16_WIDTH__ = @as(c_int, 16);
pub const INT_LEAST16_FMTd__ = "hd";
pub const INT_LEAST16_FMTi__ = "hi";
pub const __UINT_LEAST16_TYPE__ = c_ushort;
pub const __UINT_LEAST16_MAX__ = __helpers.promoteIntLiteral(c_int, 65535, .decimal);
pub const UINT_LEAST16_FMTo__ = "ho";
pub const UINT_LEAST16_FMTu__ = "hu";
pub const UINT_LEAST16_FMTx__ = "hx";
pub const UINT_LEAST16_FMTX__ = "hX";
pub const __INT_FAST16_TYPE__ = c_short;
pub const __INT_FAST16_MAX__ = @as(c_int, 32767);
pub const __INT_FAST16_WIDTH__ = @as(c_int, 16);
pub const INT_FAST16_FMTd__ = "hd";
pub const INT_FAST16_FMTi__ = "hi";
pub const __UINT_FAST16_TYPE__ = c_ushort;
pub const __UINT_FAST16_MAX__ = __helpers.promoteIntLiteral(c_int, 65535, .decimal);
pub const UINT_FAST16_FMTo__ = "ho";
pub const UINT_FAST16_FMTu__ = "hu";
pub const UINT_FAST16_FMTx__ = "hx";
pub const UINT_FAST16_FMTX__ = "hX";
pub const __INT_LEAST32_TYPE__ = c_int;
pub const __INT_LEAST32_MAX__ = __helpers.promoteIntLiteral(c_int, 2147483647, .decimal);
pub const __INT_LEAST32_WIDTH__ = @as(c_int, 32);
pub const INT_LEAST32_FMTd__ = "d";
pub const INT_LEAST32_FMTi__ = "i";
pub const __UINT_LEAST32_TYPE__ = c_uint;
pub const __UINT_LEAST32_MAX__ = __helpers.promoteIntLiteral(c_uint, 4294967295, .decimal);
pub const UINT_LEAST32_FMTo__ = "o";
pub const UINT_LEAST32_FMTu__ = "u";
pub const UINT_LEAST32_FMTx__ = "x";
pub const UINT_LEAST32_FMTX__ = "X";
pub const __INT_FAST32_TYPE__ = c_int;
pub const __INT_FAST32_MAX__ = __helpers.promoteIntLiteral(c_int, 2147483647, .decimal);
pub const __INT_FAST32_WIDTH__ = @as(c_int, 32);
pub const INT_FAST32_FMTd__ = "d";
pub const INT_FAST32_FMTi__ = "i";
pub const __UINT_FAST32_TYPE__ = c_uint;
pub const __UINT_FAST32_MAX__ = __helpers.promoteIntLiteral(c_uint, 4294967295, .decimal);
pub const UINT_FAST32_FMTo__ = "o";
pub const UINT_FAST32_FMTu__ = "u";
pub const UINT_FAST32_FMTx__ = "x";
pub const UINT_FAST32_FMTX__ = "X";
pub const __INT_LEAST64_TYPE__ = c_long;
pub const __INT_LEAST64_MAX__ = __helpers.promoteIntLiteral(c_long, 9223372036854775807, .decimal);
pub const __INT_LEAST64_WIDTH__ = @as(c_int, 64);
pub const INT_LEAST64_FMTd__ = "ld";
pub const INT_LEAST64_FMTi__ = "li";
pub const __UINT_LEAST64_TYPE__ = c_ulong;
pub const __UINT_LEAST64_MAX__ = __helpers.promoteIntLiteral(c_ulong, 18446744073709551615, .decimal);
pub const UINT_LEAST64_FMTo__ = "lo";
pub const UINT_LEAST64_FMTu__ = "lu";
pub const UINT_LEAST64_FMTx__ = "lx";
pub const UINT_LEAST64_FMTX__ = "lX";
pub const __INT_FAST64_TYPE__ = c_long;
pub const __INT_FAST64_MAX__ = __helpers.promoteIntLiteral(c_long, 9223372036854775807, .decimal);
pub const __INT_FAST64_WIDTH__ = @as(c_int, 64);
pub const INT_FAST64_FMTd__ = "ld";
pub const INT_FAST64_FMTi__ = "li";
pub const __UINT_FAST64_TYPE__ = c_ulong;
pub const __UINT_FAST64_MAX__ = __helpers.promoteIntLiteral(c_ulong, 18446744073709551615, .decimal);
pub const UINT_FAST64_FMTo__ = "lo";
pub const UINT_FAST64_FMTu__ = "lu";
pub const UINT_FAST64_FMTx__ = "lx";
pub const UINT_FAST64_FMTX__ = "lX";
pub const __FLT16_DENORM_MIN__ = @as(f16, 5.9604644775390625e-8);
pub const __FLT16_HAS_DENORM__ = "";
pub const __FLT16_DIG__ = @as(c_int, 3);
pub const __FLT16_DECIMAL_DIG__ = @as(c_int, 5);
pub const __FLT16_EPSILON__ = @as(f16, 9.765625e-4);
pub const __FLT16_HAS_INFINITY__ = "";
pub const __FLT16_HAS_QUIET_NAN__ = "";
pub const __FLT16_MANT_DIG__ = @as(c_int, 11);
pub const __FLT16_MAX_10_EXP__ = @as(c_int, 4);
pub const __FLT16_MAX_EXP__ = @as(c_int, 16);
pub const __FLT16_MAX__ = @as(f16, 6.5504e+4);
pub const __FLT16_MIN_10_EXP__ = -@as(c_int, 4);
pub const __FLT16_MIN_EXP__ = -@as(c_int, 13);
pub const __FLT16_MIN__ = @as(f16, 6.103515625e-5);
pub const __FLT_DENORM_MIN__ = @as(f32, 1.40129846e-45);
pub const __FLT_HAS_DENORM__ = "";
pub const __FLT_DIG__ = @as(c_int, 6);
pub const __FLT_DECIMAL_DIG__ = @as(c_int, 9);
pub const __FLT_EPSILON__ = @as(f32, 1.19209290e-7);
pub const __FLT_HAS_INFINITY__ = "";
pub const __FLT_HAS_QUIET_NAN__ = "";
pub const __FLT_MANT_DIG__ = @as(c_int, 24);
pub const __FLT_MAX_10_EXP__ = @as(c_int, 38);
pub const __FLT_MAX_EXP__ = @as(c_int, 128);
pub const __FLT_MAX__ = @as(f32, 3.40282347e+38);
pub const __FLT_MIN_10_EXP__ = -@as(c_int, 37);
pub const __FLT_MIN_EXP__ = -@as(c_int, 125);
pub const __FLT_MIN__ = @as(f32, 1.17549435e-38);
pub const __DBL_DENORM_MIN__ = @as(f64, 4.9406564584124654e-324);
pub const __DBL_HAS_DENORM__ = "";
pub const __DBL_DIG__ = @as(c_int, 15);
pub const __DBL_DECIMAL_DIG__ = @as(c_int, 17);
pub const __DBL_EPSILON__ = @as(f64, 2.2204460492503131e-16);
pub const __DBL_HAS_INFINITY__ = "";
pub const __DBL_HAS_QUIET_NAN__ = "";
pub const __DBL_MANT_DIG__ = @as(c_int, 53);
pub const __DBL_MAX_10_EXP__ = @as(c_int, 308);
pub const __DBL_MAX_EXP__ = @as(c_int, 1024);
pub const __DBL_MAX__ = @as(f64, 1.7976931348623157e+308);
pub const __DBL_MIN_10_EXP__ = -@as(c_int, 307);
pub const __DBL_MIN_EXP__ = -@as(c_int, 1021);
pub const __DBL_MIN__ = @as(f64, 2.2250738585072014e-308);
pub const __LDBL_DENORM_MIN__ = @as(c_longdouble, 3.64519953188247460253e-4951);
pub const __LDBL_HAS_DENORM__ = "";
pub const __LDBL_DIG__ = @as(c_int, 18);
pub const __LDBL_DECIMAL_DIG__ = @as(c_int, 21);
pub const __LDBL_EPSILON__ = @as(c_longdouble, 1.08420217248550443401e-19);
pub const __LDBL_HAS_INFINITY__ = "";
pub const __LDBL_HAS_QUIET_NAN__ = "";
pub const __LDBL_MANT_DIG__ = @as(c_int, 64);
pub const __LDBL_MAX_10_EXP__ = @as(c_int, 4932);
pub const __LDBL_MAX_EXP__ = @as(c_int, 16384);
pub const __LDBL_MAX__ = @as(c_longdouble, 1.18973149535723176502e+4932);
pub const __LDBL_MIN_10_EXP__ = -@as(c_int, 4931);
pub const __LDBL_MIN_EXP__ = -@as(c_int, 16381);
pub const __LDBL_MIN__ = @as(c_longdouble, 3.36210314311209350626e-4932);
pub const __FLT_EVAL_METHOD__ = @as(c_int, 0);
pub const __FLT_RADIX__ = @as(c_int, 2);
pub const __DECIMAL_DIG__ = __LDBL_DECIMAL_DIG__;
pub const __pic__ = @as(c_int, 2);
pub const __PIC__ = @as(c_int, 2);
pub const NDEBUG = @as(c_int, 1);
pub const _UNISTD_H = "";
pub const _FEATURES_H = "";
pub const _BSD_SOURCE = @as(c_int, 1);
pub const _XOPEN_SOURCE = @as(c_int, 700);
pub const __restrict = @compileError("unable to translate C expr: unexpected token 'restrict'"); // /usr/include/features.h:20:9
pub const __inline = @compileError("unable to translate C expr: unexpected token 'inline'"); // /usr/include/features.h:26:9
pub const __REDIR = @compileError("unable to translate C expr: unexpected token '__typeof__'"); // /usr/include/features.h:38:9
pub const STDIN_FILENO = @as(c_int, 0);
pub const STDOUT_FILENO = @as(c_int, 1);
pub const STDERR_FILENO = @as(c_int, 2);
pub const SEEK_SET = @as(c_int, 0);
pub const SEEK_CUR = @as(c_int, 1);
pub const SEEK_END = @as(c_int, 2);
pub const SEEK_DATA = @as(c_int, 3);
pub const SEEK_HOLE = @as(c_int, 4);
pub const NULL = __helpers.cast(?*anyopaque, @as(c_int, 0));
pub const __NEED_size_t = "";
pub const __NEED_ssize_t = "";
pub const __NEED_uid_t = "";
pub const __NEED_gid_t = "";
pub const __NEED_off_t = "";
pub const __NEED_pid_t = "";
pub const __NEED_intptr_t = "";
pub const __NEED_useconds_t = "";
pub const __BYTE_ORDER = @as(c_int, 1234);
pub const __LONG_MAX = __helpers.promoteIntLiteral(c_long, 0x7fffffffffffffff, .hex);
pub const __LITTLE_ENDIAN = @as(c_int, 1234);
pub const __BIG_ENDIAN = @as(c_int, 4321);
pub const __USE_TIME_BITS64 = @as(c_int, 1);
pub const __DEFINED_size_t = "";
pub const __DEFINED_ssize_t = "";
pub const __DEFINED_intptr_t = "";
pub const __DEFINED_off_t = "";
pub const __DEFINED_pid_t = "";
pub const __DEFINED_uid_t = "";
pub const __DEFINED_gid_t = "";
pub const __DEFINED_useconds_t = "";
pub const F_OK = @as(c_int, 0);
pub const R_OK = @as(c_int, 4);
pub const W_OK = @as(c_int, 2);
pub const X_OK = @as(c_int, 1);
pub const F_ULOCK = @as(c_int, 0);
pub const F_LOCK = @as(c_int, 1);
pub const F_TLOCK = @as(c_int, 2);
pub const F_TEST = @as(c_int, 3);
pub const L_SET = @as(c_int, 0);
pub const L_INCR = @as(c_int, 1);
pub const L_XTND = @as(c_int, 2);
pub const POSIX_CLOSE_RESTART = @as(c_int, 0);
pub const _XOPEN_VERSION = @as(c_int, 700);
pub const _XOPEN_UNIX = @as(c_int, 1);
pub const _XOPEN_ENH_I18N = @as(c_int, 1);
pub const _POSIX_VERSION = @as(c_long, 200809);
pub const _POSIX2_VERSION = _POSIX_VERSION;
pub const _POSIX_ADVISORY_INFO = _POSIX_VERSION;
pub const _POSIX_CHOWN_RESTRICTED = @as(c_int, 1);
pub const _POSIX_IPV6 = _POSIX_VERSION;
pub const _POSIX_JOB_CONTROL = @as(c_int, 1);
pub const _POSIX_MAPPED_FILES = _POSIX_VERSION;
pub const _POSIX_MEMLOCK = _POSIX_VERSION;
pub const _POSIX_MEMLOCK_RANGE = _POSIX_VERSION;
pub const _POSIX_MEMORY_PROTECTION = _POSIX_VERSION;
pub const _POSIX_MESSAGE_PASSING = _POSIX_VERSION;
pub const _POSIX_FSYNC = _POSIX_VERSION;
pub const _POSIX_NO_TRUNC = @as(c_int, 1);
pub const _POSIX_RAW_SOCKETS = _POSIX_VERSION;
pub const _POSIX_REALTIME_SIGNALS = _POSIX_VERSION;
pub const _POSIX_REGEXP = @as(c_int, 1);
pub const _POSIX_SAVED_IDS = @as(c_int, 1);
pub const _POSIX_SHELL = @as(c_int, 1);
pub const _POSIX_SPAWN = _POSIX_VERSION;
pub const _POSIX_VDISABLE = @as(c_int, 0);
pub const _POSIX_THREADS = _POSIX_VERSION;
pub const _POSIX_THREAD_PROCESS_SHARED = _POSIX_VERSION;
pub const _POSIX_THREAD_SAFE_FUNCTIONS = _POSIX_VERSION;
pub const _POSIX_THREAD_ATTR_STACKADDR = _POSIX_VERSION;
pub const _POSIX_THREAD_ATTR_STACKSIZE = _POSIX_VERSION;
pub const _POSIX_THREAD_PRIORITY_SCHEDULING = _POSIX_VERSION;
pub const _POSIX_THREAD_CPUTIME = _POSIX_VERSION;
pub const _POSIX_TIMERS = _POSIX_VERSION;
pub const _POSIX_TIMEOUTS = _POSIX_VERSION;
pub const _POSIX_MONOTONIC_CLOCK = _POSIX_VERSION;
pub const _POSIX_CPUTIME = _POSIX_VERSION;
pub const _POSIX_CLOCK_SELECTION = _POSIX_VERSION;
pub const _POSIX_BARRIERS = _POSIX_VERSION;
pub const _POSIX_SPIN_LOCKS = _POSIX_VERSION;
pub const _POSIX_READER_WRITER_LOCKS = _POSIX_VERSION;
pub const _POSIX_ASYNCHRONOUS_IO = _POSIX_VERSION;
pub const _POSIX_SEMAPHORES = _POSIX_VERSION;
pub const _POSIX_SHARED_MEMORY_OBJECTS = _POSIX_VERSION;
pub const _POSIX2_C_BIND = _POSIX_VERSION;
pub const _POSIX_V6_LP64_OFF64 = @as(c_int, 1);
pub const _POSIX_V7_LP64_OFF64 = @as(c_int, 1);
pub const _PC_LINK_MAX = @as(c_int, 0);
pub const _PC_MAX_CANON = @as(c_int, 1);
pub const _PC_MAX_INPUT = @as(c_int, 2);
pub const _PC_NAME_MAX = @as(c_int, 3);
pub const _PC_PATH_MAX = @as(c_int, 4);
pub const _PC_PIPE_BUF = @as(c_int, 5);
pub const _PC_CHOWN_RESTRICTED = @as(c_int, 6);
pub const _PC_NO_TRUNC = @as(c_int, 7);
pub const _PC_VDISABLE = @as(c_int, 8);
pub const _PC_SYNC_IO = @as(c_int, 9);
pub const _PC_ASYNC_IO = @as(c_int, 10);
pub const _PC_PRIO_IO = @as(c_int, 11);
pub const _PC_SOCK_MAXBUF = @as(c_int, 12);
pub const _PC_FILESIZEBITS = @as(c_int, 13);
pub const _PC_REC_INCR_XFER_SIZE = @as(c_int, 14);
pub const _PC_REC_MAX_XFER_SIZE = @as(c_int, 15);
pub const _PC_REC_MIN_XFER_SIZE = @as(c_int, 16);
pub const _PC_REC_XFER_ALIGN = @as(c_int, 17);
pub const _PC_ALLOC_SIZE_MIN = @as(c_int, 18);
pub const _PC_SYMLINK_MAX = @as(c_int, 19);
pub const _PC_2_SYMLINKS = @as(c_int, 20);
pub const _SC_ARG_MAX = @as(c_int, 0);
pub const _SC_CHILD_MAX = @as(c_int, 1);
pub const _SC_CLK_TCK = @as(c_int, 2);
pub const _SC_NGROUPS_MAX = @as(c_int, 3);
pub const _SC_OPEN_MAX = @as(c_int, 4);
pub const _SC_STREAM_MAX = @as(c_int, 5);
pub const _SC_TZNAME_MAX = @as(c_int, 6);
pub const _SC_JOB_CONTROL = @as(c_int, 7);
pub const _SC_SAVED_IDS = @as(c_int, 8);
pub const _SC_REALTIME_SIGNALS = @as(c_int, 9);
pub const _SC_PRIORITY_SCHEDULING = @as(c_int, 10);
pub const _SC_TIMERS = @as(c_int, 11);
pub const _SC_ASYNCHRONOUS_IO = @as(c_int, 12);
pub const _SC_PRIORITIZED_IO = @as(c_int, 13);
pub const _SC_SYNCHRONIZED_IO = @as(c_int, 14);
pub const _SC_FSYNC = @as(c_int, 15);
pub const _SC_MAPPED_FILES = @as(c_int, 16);
pub const _SC_MEMLOCK = @as(c_int, 17);
pub const _SC_MEMLOCK_RANGE = @as(c_int, 18);
pub const _SC_MEMORY_PROTECTION = @as(c_int, 19);
pub const _SC_MESSAGE_PASSING = @as(c_int, 20);
pub const _SC_SEMAPHORES = @as(c_int, 21);
pub const _SC_SHARED_MEMORY_OBJECTS = @as(c_int, 22);
pub const _SC_AIO_LISTIO_MAX = @as(c_int, 23);
pub const _SC_AIO_MAX = @as(c_int, 24);
pub const _SC_AIO_PRIO_DELTA_MAX = @as(c_int, 25);
pub const _SC_DELAYTIMER_MAX = @as(c_int, 26);
pub const _SC_MQ_OPEN_MAX = @as(c_int, 27);
pub const _SC_MQ_PRIO_MAX = @as(c_int, 28);
pub const _SC_VERSION = @as(c_int, 29);
pub const _SC_PAGE_SIZE = @as(c_int, 30);
pub const _SC_PAGESIZE = @as(c_int, 30);
pub const _SC_RTSIG_MAX = @as(c_int, 31);
pub const _SC_SEM_NSEMS_MAX = @as(c_int, 32);
pub const _SC_SEM_VALUE_MAX = @as(c_int, 33);
pub const _SC_SIGQUEUE_MAX = @as(c_int, 34);
pub const _SC_TIMER_MAX = @as(c_int, 35);
pub const _SC_BC_BASE_MAX = @as(c_int, 36);
pub const _SC_BC_DIM_MAX = @as(c_int, 37);
pub const _SC_BC_SCALE_MAX = @as(c_int, 38);
pub const _SC_BC_STRING_MAX = @as(c_int, 39);
pub const _SC_COLL_WEIGHTS_MAX = @as(c_int, 40);
pub const _SC_EXPR_NEST_MAX = @as(c_int, 42);
pub const _SC_LINE_MAX = @as(c_int, 43);
pub const _SC_RE_DUP_MAX = @as(c_int, 44);
pub const _SC_2_VERSION = @as(c_int, 46);
pub const _SC_2_C_BIND = @as(c_int, 47);
pub const _SC_2_C_DEV = @as(c_int, 48);
pub const _SC_2_FORT_DEV = @as(c_int, 49);
pub const _SC_2_FORT_RUN = @as(c_int, 50);
pub const _SC_2_SW_DEV = @as(c_int, 51);
pub const _SC_2_LOCALEDEF = @as(c_int, 52);
pub const _SC_UIO_MAXIOV = @as(c_int, 60);
pub const _SC_IOV_MAX = @as(c_int, 60);
pub const _SC_THREADS = @as(c_int, 67);
pub const _SC_THREAD_SAFE_FUNCTIONS = @as(c_int, 68);
pub const _SC_GETGR_R_SIZE_MAX = @as(c_int, 69);
pub const _SC_GETPW_R_SIZE_MAX = @as(c_int, 70);
pub const _SC_LOGIN_NAME_MAX = @as(c_int, 71);
pub const _SC_TTY_NAME_MAX = @as(c_int, 72);
pub const _SC_THREAD_DESTRUCTOR_ITERATIONS = @as(c_int, 73);
pub const _SC_THREAD_KEYS_MAX = @as(c_int, 74);
pub const _SC_THREAD_STACK_MIN = @as(c_int, 75);
pub const _SC_THREAD_THREADS_MAX = @as(c_int, 76);
pub const _SC_THREAD_ATTR_STACKADDR = @as(c_int, 77);
pub const _SC_THREAD_ATTR_STACKSIZE = @as(c_int, 78);
pub const _SC_THREAD_PRIORITY_SCHEDULING = @as(c_int, 79);
pub const _SC_THREAD_PRIO_INHERIT = @as(c_int, 80);
pub const _SC_THREAD_PRIO_PROTECT = @as(c_int, 81);
pub const _SC_THREAD_PROCESS_SHARED = @as(c_int, 82);
pub const _SC_NPROCESSORS_CONF = @as(c_int, 83);
pub const _SC_NPROCESSORS_ONLN = @as(c_int, 84);
pub const _SC_PHYS_PAGES = @as(c_int, 85);
pub const _SC_AVPHYS_PAGES = @as(c_int, 86);
pub const _SC_ATEXIT_MAX = @as(c_int, 87);
pub const _SC_PASS_MAX = @as(c_int, 88);
pub const _SC_XOPEN_VERSION = @as(c_int, 89);
pub const _SC_XOPEN_XCU_VERSION = @as(c_int, 90);
pub const _SC_XOPEN_UNIX = @as(c_int, 91);
pub const _SC_XOPEN_CRYPT = @as(c_int, 92);
pub const _SC_XOPEN_ENH_I18N = @as(c_int, 93);
pub const _SC_XOPEN_SHM = @as(c_int, 94);
pub const _SC_2_CHAR_TERM = @as(c_int, 95);
pub const _SC_2_UPE = @as(c_int, 97);
pub const _SC_XOPEN_XPG2 = @as(c_int, 98);
pub const _SC_XOPEN_XPG3 = @as(c_int, 99);
pub const _SC_XOPEN_XPG4 = @as(c_int, 100);
pub const _SC_NZERO = @as(c_int, 109);
pub const _SC_XBS5_ILP32_OFF32 = @as(c_int, 125);
pub const _SC_XBS5_ILP32_OFFBIG = @as(c_int, 126);
pub const _SC_XBS5_LP64_OFF64 = @as(c_int, 127);
pub const _SC_XBS5_LPBIG_OFFBIG = @as(c_int, 128);
pub const _SC_XOPEN_LEGACY = @as(c_int, 129);
pub const _SC_XOPEN_REALTIME = @as(c_int, 130);
pub const _SC_XOPEN_REALTIME_THREADS = @as(c_int, 131);
pub const _SC_ADVISORY_INFO = @as(c_int, 132);
pub const _SC_BARRIERS = @as(c_int, 133);
pub const _SC_CLOCK_SELECTION = @as(c_int, 137);
pub const _SC_CPUTIME = @as(c_int, 138);
pub const _SC_THREAD_CPUTIME = @as(c_int, 139);
pub const _SC_MONOTONIC_CLOCK = @as(c_int, 149);
pub const _SC_READER_WRITER_LOCKS = @as(c_int, 153);
pub const _SC_SPIN_LOCKS = @as(c_int, 154);
pub const _SC_REGEXP = @as(c_int, 155);
pub const _SC_SHELL = @as(c_int, 157);
pub const _SC_SPAWN = @as(c_int, 159);
pub const _SC_SPORADIC_SERVER = @as(c_int, 160);
pub const _SC_THREAD_SPORADIC_SERVER = @as(c_int, 161);
pub const _SC_TIMEOUTS = @as(c_int, 164);
pub const _SC_TYPED_MEMORY_OBJECTS = @as(c_int, 165);
pub const _SC_2_PBS = @as(c_int, 168);
pub const _SC_2_PBS_ACCOUNTING = @as(c_int, 169);
pub const _SC_2_PBS_LOCATE = @as(c_int, 170);
pub const _SC_2_PBS_MESSAGE = @as(c_int, 171);
pub const _SC_2_PBS_TRACK = @as(c_int, 172);
pub const _SC_SYMLOOP_MAX = @as(c_int, 173);
pub const _SC_STREAMS = @as(c_int, 174);
pub const _SC_2_PBS_CHECKPOINT = @as(c_int, 175);
pub const _SC_V6_ILP32_OFF32 = @as(c_int, 176);
pub const _SC_V6_ILP32_OFFBIG = @as(c_int, 177);
pub const _SC_V6_LP64_OFF64 = @as(c_int, 178);
pub const _SC_V6_LPBIG_OFFBIG = @as(c_int, 179);
pub const _SC_HOST_NAME_MAX = @as(c_int, 180);
pub const _SC_TRACE = @as(c_int, 181);
pub const _SC_TRACE_EVENT_FILTER = @as(c_int, 182);
pub const _SC_TRACE_INHERIT = @as(c_int, 183);
pub const _SC_TRACE_LOG = @as(c_int, 184);
pub const _SC_IPV6 = @as(c_int, 235);
pub const _SC_RAW_SOCKETS = @as(c_int, 236);
pub const _SC_V7_ILP32_OFF32 = @as(c_int, 237);
pub const _SC_V7_ILP32_OFFBIG = @as(c_int, 238);
pub const _SC_V7_LP64_OFF64 = @as(c_int, 239);
pub const _SC_V7_LPBIG_OFFBIG = @as(c_int, 240);
pub const _SC_SS_REPL_MAX = @as(c_int, 241);
pub const _SC_TRACE_EVENT_NAME_MAX = @as(c_int, 242);
pub const _SC_TRACE_NAME_MAX = @as(c_int, 243);
pub const _SC_TRACE_SYS_MAX = @as(c_int, 244);
pub const _SC_TRACE_USER_EVENT_MAX = @as(c_int, 245);
pub const _SC_XOPEN_STREAMS = @as(c_int, 246);
pub const _SC_THREAD_ROBUST_PRIO_INHERIT = @as(c_int, 247);
pub const _SC_THREAD_ROBUST_PRIO_PROTECT = @as(c_int, 248);
pub const _SC_MINSIGSTKSZ = @as(c_int, 249);
pub const _SC_SIGSTKSZ = @as(c_int, 250);
pub const _CS_PATH = @as(c_int, 0);
pub const _CS_POSIX_V6_WIDTH_RESTRICTED_ENVS = @as(c_int, 1);
pub const _CS_GNU_LIBC_VERSION = @as(c_int, 2);
pub const _CS_GNU_LIBPTHREAD_VERSION = @as(c_int, 3);
pub const _CS_POSIX_V5_WIDTH_RESTRICTED_ENVS = @as(c_int, 4);
pub const _CS_POSIX_V7_WIDTH_RESTRICTED_ENVS = @as(c_int, 5);
pub const _CS_POSIX_V6_ILP32_OFF32_CFLAGS = @as(c_int, 1116);
pub const _CS_POSIX_V6_ILP32_OFF32_LDFLAGS = @as(c_int, 1117);
pub const _CS_POSIX_V6_ILP32_OFF32_LIBS = @as(c_int, 1118);
pub const _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS = @as(c_int, 1119);
pub const _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS = @as(c_int, 1120);
pub const _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS = @as(c_int, 1121);
pub const _CS_POSIX_V6_ILP32_OFFBIG_LIBS = @as(c_int, 1122);
pub const _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS = @as(c_int, 1123);
pub const _CS_POSIX_V6_LP64_OFF64_CFLAGS = @as(c_int, 1124);
pub const _CS_POSIX_V6_LP64_OFF64_LDFLAGS = @as(c_int, 1125);
pub const _CS_POSIX_V6_LP64_OFF64_LIBS = @as(c_int, 1126);
pub const _CS_POSIX_V6_LP64_OFF64_LINTFLAGS = @as(c_int, 1127);
pub const _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS = @as(c_int, 1128);
pub const _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS = @as(c_int, 1129);
pub const _CS_POSIX_V6_LPBIG_OFFBIG_LIBS = @as(c_int, 1130);
pub const _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS = @as(c_int, 1131);
pub const _CS_POSIX_V7_ILP32_OFF32_CFLAGS = @as(c_int, 1132);
pub const _CS_POSIX_V7_ILP32_OFF32_LDFLAGS = @as(c_int, 1133);
pub const _CS_POSIX_V7_ILP32_OFF32_LIBS = @as(c_int, 1134);
pub const _CS_POSIX_V7_ILP32_OFF32_LINTFLAGS = @as(c_int, 1135);
pub const _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS = @as(c_int, 1136);
pub const _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS = @as(c_int, 1137);
pub const _CS_POSIX_V7_ILP32_OFFBIG_LIBS = @as(c_int, 1138);
pub const _CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS = @as(c_int, 1139);
pub const _CS_POSIX_V7_LP64_OFF64_CFLAGS = @as(c_int, 1140);
pub const _CS_POSIX_V7_LP64_OFF64_LDFLAGS = @as(c_int, 1141);
pub const _CS_POSIX_V7_LP64_OFF64_LIBS = @as(c_int, 1142);
pub const _CS_POSIX_V7_LP64_OFF64_LINTFLAGS = @as(c_int, 1143);
pub const _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS = @as(c_int, 1144);
pub const _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS = @as(c_int, 1145);
pub const _CS_POSIX_V7_LPBIG_OFFBIG_LIBS = @as(c_int, 1146);
pub const _CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS = @as(c_int, 1147);
pub const _CS_V6_ENV = @as(c_int, 1148);
pub const _CS_V7_ENV = @as(c_int, 1149);
pub const _CS_POSIX_V7_THREADS_CFLAGS = @as(c_int, 1150);
pub const _CS_POSIX_V7_THREADS_LDFLAGS = @as(c_int, 1151);
pub const _STDLIB_H = "";
pub const __NEED_wchar_t = "";
pub const __DEFINED_wchar_t = "";
pub const EXIT_FAILURE = @as(c_int, 1);
pub const EXIT_SUCCESS = @as(c_int, 0);
pub const MB_CUR_MAX = __ctype_get_mb_cur_max();
pub const RAND_MAX = __helpers.promoteIntLiteral(c_int, 0x7fffffff, .hex);
pub const WNOHANG = @as(c_int, 1);
pub const WUNTRACED = @as(c_int, 2);
pub inline fn WEXITSTATUS(s: anytype) @TypeOf((s & __helpers.promoteIntLiteral(c_int, 0xff00, .hex)) >> @as(c_int, 8)) {
    _ = &s;
    return (s & __helpers.promoteIntLiteral(c_int, 0xff00, .hex)) >> @as(c_int, 8);
}
pub inline fn WTERMSIG(s: anytype) @TypeOf(s & @as(c_int, 0x7f)) {
    _ = &s;
    return s & @as(c_int, 0x7f);
}
pub inline fn WSTOPSIG(s: anytype) @TypeOf(WEXITSTATUS(s)) {
    _ = &s;
    return WEXITSTATUS(s);
}
pub inline fn WIFEXITED(s: anytype) @TypeOf(!(WTERMSIG(s) != 0)) {
    _ = &s;
    return !(WTERMSIG(s) != 0);
}
pub inline fn WIFSTOPPED(s: anytype) @TypeOf(__helpers.cast(c_short, ((s & __helpers.promoteIntLiteral(c_int, 0xffff, .hex)) * __helpers.promoteIntLiteral(c_uint, 0x10001, .hex)) >> @as(c_int, 8)) > @as(c_int, 0x7f00)) {
    _ = &s;
    return __helpers.cast(c_short, ((s & __helpers.promoteIntLiteral(c_int, 0xffff, .hex)) * __helpers.promoteIntLiteral(c_uint, 0x10001, .hex)) >> @as(c_int, 8)) > @as(c_int, 0x7f00);
}
pub inline fn WIFSIGNALED(s: anytype) @TypeOf(((s & __helpers.promoteIntLiteral(c_int, 0xffff, .hex)) - @as(c_uint, 1)) < @as(c_uint, 0xff)) {
    _ = &s;
    return ((s & __helpers.promoteIntLiteral(c_int, 0xffff, .hex)) - @as(c_uint, 1)) < @as(c_uint, 0xff);
}
pub const _ALLOCA_H = "";
pub inline fn WCOREDUMP(s: anytype) @TypeOf(s & @as(c_int, 0x80)) {
    _ = &s;
    return s & @as(c_int, 0x80);
}
pub inline fn WIFCONTINUED(s: anytype) @TypeOf(s == __helpers.promoteIntLiteral(c_int, 0xffff, .hex)) {
    _ = &s;
    return s == __helpers.promoteIntLiteral(c_int, 0xffff, .hex);
}
